[package]
name = "elephantry-benchmark"
version = "0.1.0"
authors = ["Sanpi <sanpi@homecomputing.fr>"]
edition = "2018"

[workspace]
members = [
    "diesel",
    "elephantry",
    "libpq",
    "postgres",
    "sqlx",
]
