[package]
name = "diesel-bench"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4"

[dependencies.diesel]
version = "1.4"
features = ["postgres", "chrono"]

[dependencies.elephantry-benchmark]
path = "../"
version = "0.1"
