[package]
name = "diesel-bench"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4"
uuid = "1.0"

[dependencies.diesel]
version = "2.0"
features = ["postgres", "chrono", "uuid"]

[dependencies.elephantry-benchmark]
path = "../"
version = "0.1"
