[package]
name = "diesel-bench"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4"
uuid = "0.8"

[dependencies.diesel]
version = "2.0"
features = ["postgres", "chrono", "uuidv07"]

[dependencies.elephantry-benchmark]
path = "../"
version = "0.1"
