[package]
name = "libpq-bench"
version = "0.1.0"
edition.workspace = true

[dependencies]
chrono = "0.4"
libpq = "3.0"

[dependencies.elephantry-benchmark]
path = "../"
version = "0.1"

[dependencies.uuid]
version = "1.0"
features = ["v4"]
