[package]
name = "elephantry-bench"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4"

[dependencies.elephantry-benchmark]
path = "../"
version = "0.1"

[dependencies.elephantry]
version = "2.1"
features = ["date"]
