[package]
name = "postgres-bench"
version = "0.1.0"
edition = "2018"

[dependencies]
chrono = "0.4"

[dependencies.postgres]
version = "0.19"
features = ["with-chrono-0_4"]

[dependencies.elephantry-benchmark]
path = "../"
version = "0.1"
